# Generated by Django 3.0.8 on 2020-08-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='sanji.jpg', null=True, upload_to='static/image'),
        ),
    ]
