# Generated by Django 3.0.8 on 2020-08-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20200829_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
